toolbar:
  - stylesheet | formatselect | bold italic strikethrough forecolor backcolor | link | alignleft aligncenter alignright alignjustify  | numlist bullist outdent indent  | removeformat
  - image | link
plugins:
  - image
  - link
  - table 
  - colorpicker